spring.application.name=sistema-mail-OdontoCool

# Importar el archivo .env como propiedades
spring.config.import=optional:file:.env[.properties]

# ============================================
# CONFIGURACION DE BASE DE DATOS
# ============================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# CONFIGURACION SMTP (SOCKETS MANUAL)
# ============================================
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.user=${SMTP_USER}
mail.smtp.password=${SMTP_PASS}
mail.smtp.ssl=true

# ============================================
# CONFIGURACION POP3 (SOCKETS MANUAL)
# ============================================
mail.pop3.host=pop.gmail.com
mail.pop3.port=995
mail.pop3.user=${POP3_USER}
mail.pop3.password=${POP3_PASS}
mail.pop3.ssl=true