package smail.sistema_mail_OdontoCool.services;

import java.io.IOException;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class HelpService {

    @Autowired
    private SmtpClientService smtpService;

    public void sendHelp(String to, String messageError) {
        String message = ""
                + messageError + "\n"
                + "========================================\n"
                + "AYUDA - SISTEMA ODONTOCOOL (CORREO)\n"
                + "========================================\n\n"
                + "FORMATO GENERAL DE COMANDOS:\n"
                + "  COMANDO[\"param1\", \"param2\", ...]\n\n"
                + "1. DOCTORES (DOC):\n"
                + "   - Registrar un nuevo doctor:\n"
                + "     INSDOC[\"CI\", \"Nombres\", \"Apellidos\", \"Direccion\", \"Genero\", \"Telf\", \"FechaNacimiento\", \"Exp\", \"Matrícula\", \"TelfProf\", \"Correo\", \"Contraseña\"]\n"
                + "        Ejemplo: INSDOC[\"12345678\", \"Juan\", \"Perez\", \"Calle Falsa 123\", \"M\", \"55512348\", \"1980-01-01\", \"10 años\", \"MAT-001\", \"77777777\", \"juan@gmail.com\", \"p123\"]\n"
                + "        *Nota: Se debe adjuntar una imagen al correo para registrar la foto de perfil.*\n"
                + "   - Modificar los datos de un doctor:\n"
                + "     MODDOC[\"CI\", \"Nombres\", \"Apellidos\", \"Direccion\", \"Genero\", \"Telf\", \"FechaNacimiento\", \"Exp\", \"Matrícula\", \"TelfProf\", \"Correo\", \"Contraseña\"]\n"
                + "        Ejemplo: MODDOC[\"12345678\", \"Juan Carlos\", \"Perez\", \"Calle Falsa 124\", \"M\", \"55512348\", \"1980-01-01\", \"12 años\", \"MAT-001\", \"77777777\", \"juan@gmail.com\", \"p123new\"]\n"
                + "        *Nota: Opcionalmente se puede adjuntar una nueva imagen para cambiar la foto de perfil.*\n"
                + "   - Eliminar un doctor:\n"
                + "     DELDOC[\"CI\"]\n"
                + "        Ejemplo: DELDOC[\"12345678\"]\n"
                + "   - Listar todos los doctores o buscar por Nombre/CI:\n"
                + "     LISDOC[\"*\" o \"nombre_o_ci\"]\n"
                + "        Ejemplo: LISDOC[\"*\"] o LISDOC[\"Juan\"] o LISDOC[\"12345678\"]\n\n"
                + "   - Asignar una especialidad a un doctor:\n"
                + "     ASEDOC[\"CI Doctor\", \"UUID Especialidad\"]\n"
                + "2. PACIENTES (PAC):\n"
                + "   - Registrar un nuevo paciente:\n"
                + "     INSPAC[\"CI\", \"Nombres\", \"Apellidos\", \"Direccion\", \"Genero\", \"Telf\", \"FechaNacimiento\", \"ContactoEmerg\", \"TelfEmerg\", \"Correo\", \"Contraseña\"]\n"
                + "        Ejemplo: INSPAC[\"87654321\", \"Maria\", \"Gomez\", \"Av. Siempre Viva 456\", \"F\", \"55512348\", \"1990-02-02\", \"Carlos Gomez\", \"555-8765\", \"maria@gmail.com\", \"m456\"]\n"
                + "        *Nota: Se debe adjuntar una imagen al correo para registrar la foto de perfil.*\n"
                + "   - Modificar los datos de un paciente:\n"
                + "     MODPAC[\"CI\", \"Nombres\", \"Apellidos\", \"Direccion\", \"Genero\", \"Telf\", \"FechaNacimiento\", \"ContactoEmerg\", \"TelfEmerg\", \"Correo\", \"Contraseña\"]\n"
                + "        Ejemplo: MODPAC[\"87654321\", \"Maria Luz\", \"Gomez\", \"Av. Siempre Viva 457\", \"F\", \"55512348\", \"1990-02-02\", \"Carlos Gomez\", \"555-8765\", \"maria.g@gmail.com\", \"m456new\"]\n"
                + "   - Eliminar un paciente:\n"
                + "     DELPAC[\"CI\"]\n"
                + "        Ejemplo: DELPAC[\"87654321\"]\n"
                + "   - Listar todos los pacientes o buscar por Nombre/CI:\n"
                + "     LISPAC[\"*\" o \"nombre_o_ci\"]\n"
                + "        Ejemplo: LISPAC[\"*\"] o LISPAC[\"Maria\"] o LISPAC[\"87654321\"]\n\n"
                + "3. SECRETARIAS (SEC):\n"
                + "   - Registrar una nueva secretaria:\n"
                + "     INSSEC[\"CI\", \"Nombres\", \"Apellidos\", \"Direccion\", \"Genero\", \"Telf\", \"FechaNacimiento\", \"FechaContratacion\", \"Correo\", \"Contraseña\"]\n"
                + "        Ejemplo: INSSEC[\"11223344\", \"Ana\", \"Lopez\", \"Calle Luna 789\", \"F\", \"555-4321\", \"1985-03-03\", \"2010-05-01\", \"ana@gmail.com\", \"a789\"]\n"
                + "        *Nota: Se debe adjuntar una imagen al correo para registrar la foto de perfil.*\n"
                + "   - Modificar los datos de una secretaria:\n"
                + "     MODSEC[\"CI\", \"Nombres\", \"Apellidos\", \"Direccion\", \"Genero\", \"Telf\", \"FechaNacimiento\", \"FechaContratacion\", \"Correo\", \"Contraseña\"]\n"
                + "        Ejemplo: MODSEC[\"11223344\", \"Ana Maria\", \"Lopez\", \"Calle Sol 123\", \"F\", \"55512348\", \"1985-03-03\", \"2010-05-01\", \"ana.l@gmail.com\", \"a789new\"]\n"
                + "   - Eliminar una secretaria:\n"
                + "     DELSEC[\"CI\"]\n"
                + "        Ejemplo: DELSEC[\"11223344\"]\n"
                + "   - Listar todas las secretarias o buscar por Nombre/CI:\n"
                + "     LISSEC[\"*\" o \"nombre_o_ci\"]\n"
                + "        Ejemplo: LISSEC[\"*\"] o LISSEC[\"Ana\"] o LISSEC[\"11223344\"]\n\n"
                + "4. PROPIETARIOS (PRO):\n"
                + "   - Registrar un nuevo propietario:\n"
                + "     INSPRO[\"CI\", \"Nombres\", \"Apellidos\", \"Direccion\", \"Genero\", \"Telf\", \"FechaNacimiento\", \"Porcentaje\", \"Correo\", \"Contraseña\"]\n"
                + "        Ejemplo: INSPRO[\"55667788\", \"Luis\", \"Martinez\", \"Av. Sol 321\", \"M\", \"555-6789\", \"1975-04-04\", \"25.5\", \"luis@gmail.com\", \"l012\"]\n"
                + "        *Nota: Se debe adjuntar una imagen al correo para registrar la foto de perfil.*\n"
                + "   - Modificar los datos de un propietario:\n"
                + "     MODPRO[\"CI\", \"Nombres\", \"Apellidos\", \"Direccion\", \"Genero\", \"Telf\", \"FechaNacimiento\", \"Porcentaje\", \"Correo\", \"Contraseña\"]\n"
                + "        Ejemplo: MODPRO[\"55667788\", \"Luis Alberto\", \"Martinez\", \"Av. Sol 322\", \"M\", \"55512348\", \"1975-04-04\", \"30.0\", \"luis.m@gmail.com\", \"l012new\"]\n"
                + "   - Eliminar un propietario:\n"
                + "     DELPRO[\"CI\"]\n"
                + "        Ejemplo: DELPRO[\"55667788\"]\n"
                + "   - Listar todos los propietarios o buscar por Nombre/CI:\n"
                + "     LISPRO[\"*\" o \"nombre_o_ci\"]\n"
                + "        Ejemplo: LISPRO[\"*\"] o LISPRO[\"Luis\"] o LISPRO[\"55667788\"]\n\n"
                + "5. ESPECIALIDADES (ESP):\n"
                + "   - Registrar una nueva especialidad:\n"
                + "     INSESP[\"Nombre\", \"Descripcion\",\"estado\"]\n"
                + "   - Listar todas las especialidades:\n"
                + "     LISESP[*]\n\n"
                + "6. HISTORIALES CLÍNICOS (HIS):\n"
                + "   - Registrar un nuevo historial clínico para un paciente:\n"
                + "     INSHIS[\"CI_Paciente\", \"Alergias\", \"AntecedentesMedicos\", \"EnfermedadesBase\", \"MotivoApertura\", \"ObservacionesGenerales\"]\n"
                + "        Ejemplo: INSHIS[\"12345678\", \"Ninguna\", \"Operación de apéndice\", \"Ninguna\", \"Dolor de muela\", \"Paciente requiere cuidado especial\"]\n"
                + "   - Modificar los datos de un historial clínico:\n"
                + "     MODHIS[\"CodigoHistorial\", \"Alergias\", \"AntecedentesMedicos\", \"EnfermedadesBase\", \"MotivoApertura\", \"ObservacionesGenerales\"]\n"
                + "        Ejemplo: MODHIS[\"12345678P\", \"Penicilina\", \"\", \"\", \"\", \"\"]\n"
                + "   - Eliminar un historial clínico:\n"
                + "     DELHIS[\"CodigoHistorial\"]\n"
                + "   - Listar todos los historiales clínicos o buscar por código:\n"
                + "     LISHIS[\"*\" o \"codigo_historial\"]\n"
                + "        Ejemplo: LISHIS[\"*\"] o LISHIS[\"87654321G\"]\n"
                + "7. CITAS (CIT):\n"
                + "   - Registrar / programar una nueva cita médica:\n"
                + "     INSCIT[\"FechaCita\", \"HoraInicio\", \"HoraFin\", \"Motivo\", \"Observacion\", \"CI_Secretaria\", \"CI_Paciente\", \"CodigoHistorial\", \"CI_Doctor\"]\n"
                + "        Ejemplo: INSCIT[\"2026-06-01\", \"09:00\", \"09:30\", \"Consulta General\", \"Ninguna\", \"11223344\", \"87654321\", \"87654321G\", \"12345678\"]\n"
                + "   - Modificar los datos de una cita médica:\n"
                + "     MODCIT[\"IdCita\", \"FechaCita\", \"HoraInicio\", \"HoraFin\", \"Motivo\", \"Observacion\", \"CodigoHistorial\"]\n"
                + "        Ejemplo: MODCIT[\"1\", \"2026-06-01\", \"10:00\", \"10:30\", \"\", \"\", \"87654321G\"]\n"
                + "   - Eliminar (de manera lógica) una cita médica:\n"
                + "     DELCIT[\"IdCita\"]\n"
                + "   - Cancelar una cita médica:\n"
                + "     CNLCIT[\"IdCita\"]\n"
                + "   - Listar todas las citas médicas o buscar por Paciente CI/Cita ID:\n"
                + "     LISCIT[\"*\" o \"paciente_ci\" o \"id_cita\"]\n"
                + "        Ejemplo: LISCIT[\"*\"] o LISCIT[\"87654321\"] o LISCIT[\"1\"]\n\n"
                + "8. ESTADOS DE CITA (ECI):\n"
                + "   - Registrar un nuevo estado de cita:\n"
                + "     INSECI[\"Nombre\", \"Descripcion\"]\n"
                + "        Ejemplo: INSECI[\"CONFIRMADA\", \"La cita ha sido confirmada por el paciente\"]\n"
                + "   - Modificar un estado de cita:\n"
                + "     MODECI[\"IdEstadoCita\", \"Nombre\", \"Descripcion\"]\n"
                + "        Ejemplo: MODECI[\"1\", \"CANCELADA\", \"Cita cancelada\"]\n"
                + "   - Eliminar un estado de cita:\n"
                + "     DELECI[\"IdEstadoCita\"]\n"
                + "   - Listar todos los estados de cita:\n"
                + "     LISECI[*]\n"
                + "   - Asignar un estado a una cita médica:\n"
                + "     ASEECI[\"IdCita\", \"NombreEstado\", \"Observaciones\"]\n"
                + "        Ejemplo: ASEECI[\"1\", \"CONFIRMADA\", \"El paciente confirmó por llamada\"]\n"
                + "9. ANTECEDENTES ODONTOLÓGICOS (AOD):\n"
                + "   - Registrar antecedentes odontológicos para un historial:\n"
                + "     INSAOD[\"ObservacionGeneral\", \"nombreTratamiento1;descripcion1;YYYY-MM-DD;lugar1;observacion1 | ...\", \"CodHistorial\"]\n"
                + "        Ejemplo: INSAOD[\"Paciente requiere cuidados en las encías\", \"Limpieza Dental;Limpieza profunda;2026-05-29;Clínica Dental;Ninguna | Extracción;Extracción de molar;2026-05-30;Hospital Central;Paciente nervioso\", \"87654321G\"]\n"
                + "   - Modificar antecedentes odontológicos:\n"
                + "     MODAOD[\"IdAntecedente\", \"ObservacionGeneral\", \"nombreTratamiento1;descripcion1;YYYY-MM-DD;lugar1;observacion1 | ...\", \"CodHistorial\"]\n"
                + "        Ejemplo: MODAOD[\"1\", \"Observación actualizada\", \"Limpieza Dental;Nueva limpieza;2026-05-29;Clínica Dental;Ninguna\", \"\"]\n"
                + "   - Listar todos los antecedentes odontológicos:\n"
                + "     LISAOD[*]\n"
                + "   - Listar todas las especialidades:\n"
                + "     LISESP[*]\n"
                + "10. TURNOS (TUR):\n"
                + "   - Registrar un nuevo turno de trabajo:\n"
                + "     INSTUR[\"Nombre\", \"HoraInicio\", \"HoraFin\", \"Estado\"]\n"
                + "   - Listar todos los turnos de trabajo:\n"
                + "     LISTUR[*]\n"
                + "   - Modificar un turno de trabajo:\n"
                + "     MODTUR[\"ID\", \"Nombre\", \"HoraInicio\", \"HoraFin\", \"Estado\"]\n"
                + "11. ASIGNACIÓN DE TURNOS A DOCTORES (ATD):\n"
                + "   - Registrar la asignación de un turno a un doctor:\n"
                + "     INSATD[\"DiaSemana\", \"FechaInicio\", \"FechaFin\", \"Estado\", \"CI Doctor\", \"ID Turno\"]\n"
                + "        *Nota: DiaSemana solo acepta: LU, MA, MI, JU, VI, SA, DO.*\n"
                + "        Ejemplo: INSATD[\"LU\", \"2026-06-01\", \"2026-12-31\", \"Activo\", \"12345678\", \"1\"]\n"
                + "   - Listar todas las asignaciones de turnos a doctores:\n"
                + "     LISATD[*]\n"
                + "   - Modificar la asignación de un turno de un doctor:\n"
                + "     MODATD[\"ID\", \"DiaSemana\", \"FechaInicio\", \"FechaFin\", \"Estado\", \"CI Doctor\", \"ID Turno\"]\n"
                + "        Ejemplo: MODATD[\"1\", \"MA\", \"2026-06-01\", \"2026-12-31\", \"Activo\", \"12345678\", \"1\"]\n"
                + "12. ASIGNACIÓN DE TURNOS A SECRETARIAS (ATS):\n"
                + "   - Registrar la asignación de un turno a una secretaria:\n"
                + "     INSATS[\"DiaSemana\", \"FechaInicio\", \"FechaFin\", \"Estado\", \"CI Secretaria\", \"ID Turno\"]\n"
                + "        *Nota: DiaSemana solo acepta: LU, MA, MI, JU, VI, SA, DO.*\n"
                + "        Ejemplo: INSATS[\"LU\", \"2026-06-01\", \"2026-12-31\", \"Activo\", \"11223344\", \"1\"]\n"
                + "   - Listar todas las asignaciones de turnos a secretarias:\n"
                + "     LISATS[*]\n"
                + "   - Modificar la asignación de un turno de una secretaria:\n"
                + "     MODATS[\"ID\", \"DiaSemana\", \"FechaInicio\", \"FechaFin\", \"Estado\", \"CI Secretaria\", \"ID Turno\"]\n"
                + "        Ejemplo: MODATS[\"1\", \"MA\", \"2026-06-01\", \"2026-12-31\", \"Activo\", \"11223344\", \"1\"]\n"
                + "13. BOLETA DE PAGO (BPA):\n"
                + "   - Generar una nueva boleta de pago para un paciente:\n"
                + "     GENBPA[\"Descuento\", \"DetallesRaw\", \"CI_Paciente\", \"CI_Secretaria\", \"Nombre_ModoPago\", \"CantCuotas\", \"PlazoCuota\", \"MetodoPago\"]\n"
                + "        Ejemplo: GENBPA[\"10.0\", \"1 | 2 | 3\", \"12345678\", \"11223344\", \"Crédito\", \"3\", \"MES\", \"QR\"]\n"
                + "        *Nota: Modos de pago: Crédito, Contado. Plazos: MES, SEMANA. Métodos: QR. DetallesRaw recibe IDs de servicios prestados separados por '|', ';' o ','.*\n\n"
                + "   - Eliminar (de manera lógica) una boleta de pago:\n"
                + "     DELBPA[\"ID\"]\n"
                + "   - Listar todas las boletas de pago de un paciente:\n"
                + "     LISBPA[\"CI_Paciente\"]\n"
                + "        Ejemplo: LISBPA[\"12345678\"]\n\n"
                + "   - Generar el código QR para pagar una cuota:\n"
                + "     GPCBPA[\"ID_Boleta\", \"Nro_Cuota\", \"MetodoPago\"]\n"
                + "        Ejemplo: GPCBPA[\"1\", \"2\", \"QR\"]\n\n"
                + "   - Enviar comprobante de pago para procesar la cuota:\n"
                + "     EVCBPA[\"ID_Boleta\", \"Nro_Cuota\"]\n"
                + "        *Nota: Se debe adjuntar una imagen al correo para registrar el comprobante de pago.*\n\n"
                + "15. SERVICIOS (SER):\n"
                + " Registrar un nuevo servicio:\n"
                + "   - INSSER[\"Nombre\", \"Descripcion\",\"Estado\", \"Tipo\"]\n"
                + "Ejemplo: INSSER[\"Limpieza Dental\", \"Limpieza profunda para eliminar sarro y placa bacteriana\", \"ACTIVO\", \"Estética\"]\n"
                + " Listar servicios:\n"
                + "   - LISSER[*] \n"
                + "Listar servicios por tipo:\n"
                + "   - LISSER[\"Tipo:tipo\"] -> Listar servicios por tipo.\n"
                + "Ejemplo: LISSER[\"Tipo:Estética\"]\n"
                + "Modificar un servicio:\n"
                + "   - MODSER[\"ID\", \"Nombre\", \"Descripcion\", \"Estado\", \"Tipo\"]\n"
                + "Ejemplo: MODSER[\"1\", \"Limpieza Dental\", \"Limpieza profunda para eliminar sarro y placa bacteriana\", \"INACTIVO\", \"Estética\"]\n"
                + "Asignar un precio a un servicio para un tratamiento:\n"
                + "   - APSSER[\"NombreServicio\", \"FechaInicio\", \"FechaFin\", \"Moneda\", \"Monto\"]\n"
                + "EJEMPLO: APSSER[\"Limpieza Dental\", \"2026-06-01\", \"2026-06-30\", \"USD\", \"100.0\"]\n\n"
                + "17. SERVICIOS PRESTADOS (SEP):\n"
                + "Registrar uno o muchos nuevos servicios prestados para un tratamiento:\n"
                + "   - INSSEP[\"Cantidad;Precio;FechaServicio;Estado;ID Tratamiento;ID Servicio | Cantidad;Precio;FechaServicio;Estado;ID Tratamiento;ID Servicio \"]\n"
                + "Ejemplo: INSSEP[\"1;100.0;2026-06-15;PENDIENTE;1;1 | 2;200.0;2026-06-16;PENDIENTE;1;2\"]\n"
                + "Listar servicios prestados por tratamiento:\n"
                + "   - LISSEP[\"Tratamiento:ID\"] \n"
                + "Ejemplo: LISSEP[\"Tratamiento:1\"]\n"
                + "Listar todos los servicios prestados:\n"
                + "   - LISSEP[*] \n"
                + "Modificar un servicio prestado:\n"
                + "   - MODSEP[\"ID\", \"Cantidad\", \"Precio\", \"FechaServicio\", \"Estado\", \"ID Tratamiento\", \"ID Servicio\"]\n"
                + "Ejemplo: MODSEP[\"1\", \"2\", \"150.0\", \"2026-06-15\", \"COMPLETADO\", \"1\", \"1\"]\n\n"
                + "18. TRATAMIENTO DE DIENTES (TDI):\n"
                + "- Registrar un nuevo tratamiento de diente:\n"
                + "   - INSTDI[\"cara_dental;observacion;fecha_registro;estado;tratamiento_planificado;tratamiento_id;diente_id\"]\n"
                + "Ejemplo: INSTDI[\"Cara vestibular;Caries leve;2026-06-01;PLANIFICADO;Limpieza Dental;1;11\"]\n"
                + "Para insertar mas de un tratamiento de diente en el mismo comando, se pueden separar los tratamientos con '|', ';' o ','\n"
                + "Ejemplo: INSTDI[\"Cara vestibular;Caries leve;2026-06-01;PLANIFICADO;Limpieza Dental;1;11 | Cara lingual;Caries moderada;2026-06-02;PLANIFICADO;Obturación;1;11\"]\n"
                + "Listar tratamientos de dientes:\n"
                + "   - LISTDI[*]\n"
                + "Listar tratamientos de dientes para un tratamiento específico:\n"
                + "   - LISTDI[\"Tratamiento:ID\"] \n"
                + "Ejemplo: LISTDI[\"Tratamiento:1\"]\n"
                + "Modificar un tratamiento de diente:\n"
                + "   - MODTDI[\"ID\", \"CaraDental\", \"Observacion\",\" FechaRegistro\",\"Estado\",\"TratamientoPlanificado\", \"ID Tratamiento\", \"ID Diente\"]\n"
                + "Ejemplo: MODTDI[\"1\", \"Cara vestibular\", \"Caries moderada\", \"2026-06-01\", \"EN_PROGRESO\", \"Limpieza Dental\", \"1\", \"11\"]\n\n"
                + "19. DIENTES (DNT):\n"
                + "- Registrar un nuevo diente:\n"
                + "   - INSDNT[\"Nombre\", \"Número\", \"Tipo\", \"Ubicación\", \"Estado\"]\n"
                + "Ejemplo: INSDNT[\"Incisivo Central Superior Derecho\", \"11\", \"Incisivo\", \"Superior Derecho\", \"Sano\"]\n"
                + "Listar dientes:\n"
                + "   - LISDNT[*]\n"
                + "Modificar un diente:\n"
                + "   - MODDNT[\"ID\", \"Nombre\", \"Número\", \"Tipo\", \"Ubicación\", \"Estado\"]\n"
                + "Ejemplo: MODDNT[\"1\", \"Incisivo Central Superior Derecho\", \"11\", \"Incisivo\", \"Superior Derecho\", \"Caries\"]\n\n"
                + "20. TRATAMIENTOS (TRA):\n"
                + "- Registrar un nuevo tratamiento para un historial clínico:\n"
                + "   - INSTRA[\"ObjetivoTratamiento\", \"Observacion\",\"Estado\", \"FechaInicio\", \"FechaFin\",\"FechaRealFin\", \" ID Historial\", \"ID Diagnostico\"]\n"
                + "Ejemplo: INSTRA[\"Eliminar caries en molar inferior derecho\", \"Paciente presenta caries en molar inferior derecho, se recomienda limpieza dental\", \"FINALIZADO\", \"2026-06-01\", \"2026-06-30\", \"\", \"87654321G\", \"1\"]\n"
                + "- Listar tratamientos:\n"
                + "   - LISTRA[*] \n"
                + "-Listar tratamientos por historial clínico.\n"
                + "   - LISTRA[\"Historial:Codigo\"]\n"
                + "Ejemplo: LISTRA[\"Historial:87654321G\"]\n"
                + "-Buscar un tratamiento por ID.\n"
                + "   - BUSTRA[\"ID\"]\n"
                + "Ejemplo: BUSTRA[\"1\"]\n"
                + "-Modificar un tratamiento:\n"
                + "   - MODTRA[\"ID\", \"ObjetivoTratamiento\", \"Observacion\",\"Estado\", \"FechaInicio\", \"FechaFin\",\"FechaRealFin\", \" ID Historial\", \"ID Diagnostico\"]\n"
                + "Ejemplo: MODTRA[\"1\", \"Eliminar caries en molar inferior derecho\", \"Paciente presenta caries en molar inferior derecho, se recomienda limpieza dental\", \"EN_PROGRESO\", \"2026-06-01\", \"2026-06-30\", \"\", \"87654321G\", \"1\"]\n\n"
                + "21. ANÁLISIS (ANA):\n"
                + "   - Registrar un nuevo análisis:\n"
                + "   - INSANA[\"Nombre\", \"Descripcion\",\"Estado\"]\n"
                + "Ejemplo: INSANA[\"Análisis de sangre\", \"Análisis completo de sangre para evaluar el estado general del paciente\", \"ACTIVO\"]\n"
                + "   - Listar todos los análisis:\n"
                + "   - LISANA[*]\n"
                + "   - Modificar un análisis:\n"
                + "   - MODANA[\"ID\", \"Nombre\", \"Descripcion\", \"Estado\"]\n"
                + "Ejemplo: MODANA[\"1\", \"Análisis de sangre completo\", \"Análisis completo de sangre para evaluar el estado general del paciente, incluyendo hemograma y perfil lipídico\", \"ACTIVO\"]\n\n"
                + "22. SOLICITUDES DE ANÁLISIS (SOA):\n"
                + "   - Registrar una nueva solicitud de análisis para un tratamiento:\n"
                + "   - INSSOA[\"FechaSolicitud\", \"Motivo\", \"Estado\", \"ID Análisis\", \"ID Tratamiento\"]\n"
                + "Ejemplo: INSSOA[\"2026-06-10\", \"Evaluar estado general del paciente antes de procedimiento invasivo\", \"PENDIENTE\", \"1\", \"1\"]\n"
                + "- Listar todas las solicitudes de análisis:\n"
                + "   - LISSOA[*]\n"
                + "- Listar solicitudes de análisis para un tratamiento en específico.\n"
                + "   - LISSOA[\"Tratamiento:ID\"] \n"
                + "Ejemplo: LISSOA[\"Tratamiento:1\"]\n"
                + "- Modificar una solicitud de análisis:\n"
                + "   - MODSOA[\"ID\", \"FechaSolicitud\", \"Motivo\", \"Estado\", \"ID Análisis\", \"ID Tratamiento\"]\n"
                + "Ejemplo: MODSOA[\"1\", \"2026-06-11\", \"Evaluar estado general del paciente antes de procedimiento invasivo, se agregó observación de posible anemia\", \"EN_PROGRESO\", \"1\", \"1\"]\n"
                + "- Asignar una solicitud de análisis a un resultado de análisis:\n"
                + "   - AGRSOA[\"ID Solicitud\", \"fecha_resultado\", \" Resultado\",\" Observaciones\",\"Interpretacion\",\"Estado\",\"ArchivoAdjunto\"]\n"
                + "Ejemplo: AGRSOA[\"1\", \"2026-06-12\", \"Hemograma completo con resultados dentro de parámetros normales\", \"Paciente no presenta signos de anemia ni otras alteraciones hematológicas\", \"Interpretación favorable para procedimiento invasivo\", \"COMPLETADO\", \"resultado_analisis_1.pdf\"]\n\n"
                + "23. RESULTADOS DE ANÁLISIS (RAN):\n"
                + "- Modificar un resultado de análisis:\n"
                + "   - MODRAN[\"ID\", \"Resultado\", \"Observaciones\", \"Interpretacion\", \"ArchivoAdjunto\", \"Estado\", \"ID Solicitud\"]\n"
                + "Ejemplo: MODRAN[\"1\", \"Hemograma completo con resultados dentro de parámetros normales\", \"Paciente no presenta signos de anemia ni otras alteraciones hematológicas\", \"Interpretación favorable para procedimiento invasivo\", \"resultado_analisis_1.pdf\", \"COMPLETADO\", \"1\"]\n\n"
                + "24. DIAGNÓSTICOS (DIA):\n"
                + "- Registrar un nuevo diagnóstico para un tratamiento:\n"
                + "   - INSDIA[\"Sintomas\", \"TipoDiagnostico\", \"Gravedad\", \"Observaciones\", \"ID Cita\"]\n"
                + "Ejemplo: INSDIA[\"Dolor de muela\", \"Caries\", \"Leve\", \"Paciente presenta caries en molar inferior derecho\", \"1\"]\n"
                + "- Listar diagnósticos por cita médica:\n"
                + "   - LISDIA[*]\n"
                + "- Modificar un diagnóstico:\n"
                + "   - MODDIA[\"ID\", \"Sintomas\", \"TipoDiagnostico\", \"Gravedad\", \"Observaciones\", \"ID Cita\"]\n"
                + "Ejemplo: MODDIA[\"1\", \"Dolor de muela intenso\", \"Caries\", \"Moderada\", \"Paciente presenta caries en molar inferior derecho con posible afectación pulpar\", \"1\"]\n\n"
                + "25. DETALLES DE DIAGNÓSTICO (DDI):\n"
                + "- Registrar un nuevo detalle de diagnóstico para un diagnóstico:\n"
                + "   - INSDDI[\"Observacion\", \"ZonaBucal\", \"ID Diagnostico\", \"ID Diente\"]\n"
                + "Ejemplo: INSDDI[\"Caries leve en cara vestibular\", \"Cara vestibular\", \"1\", \"11\"]\n"
                + "   - Listar detalles de diagnóstico por diagnóstico:\n"
                + "   - LISDDI[*] \n"
                + "- Modificar un detalle de diagnóstico:\n"
                + "   - MODDDI[\"ID\", \"Observacion\", \"ZonaBucal\", \"ID Diagnostico\", \"ID Diente\"]\n"
                + "Ejemplo: MODDDI[\"1\", \"Caries moderada en cara vestibular\", \"Cara vestibular\", \"1\", \"11\"]\n\n"
                + "26. RECETAS/RECOMENDACIONES (RER):\n"
                + "- Registrar una nueva receta/recomendación para un tratamiento con detalles de recomendación:\n"
                + "   - INSREC[\"FechaEmision\", \"Observaciones\", \"ID Tratamiento\", \"Descripcion;Dosis;Duracion;Frecuencia | Descripcion;Dosis;Duracion;Frecuencia\"]\n"
                + "Ejemplo: INSREC[\"2026-06-15\", \"Tomar después de comer\", \"1\", \"Ibuprofeno;400mg;3 días;Cada 8 horas | Enjuague bucal;10ml;5 días;Cada noche\"]\n"
                + "- Listar recetas/recomendaciones por tratamiento:\n"
                + "- LISREC[*]\n"
                + "- Listar recetas/recomendaciones por tratamiento:\n"
                + "- LISREC[\"Tratamiento:ID\"] \n"
                + "Ejemplo: LISREC[\"Tratamiento:1\"]\n\n"
                + "27. DETALLES DE RECOMENDACIÓN (DRE):\n"
                + "- Registrar un nuevo detalle de recomendación para una receta/recomendación:\n"
                + "   - INSDRE[\"Descripcion\", \"Dosis\", \"Duracion\", \"Frecuencia\", \"ID Recomendacion\"]\n"
                + "Ejemplo: INSDRE[\"Ibuprofeno\", \"400mg\", \"3 días\", \"Cada 8 horas\", \"1\"]\n"
                + "- Listar detalles de recomendación por receta/recomendación:\n"
                + "   - LISDRE[*] \n"
                + "- Modificar un detalle de recomendación:\n"
                + "   - MODDRE[\"ID\", \"Observacion\", \"ZonaBucal\", \"ID Recomendacion\", \"ID Diente\"]\n"
                + "Ejemplo: MODDRE[\"1\", \"Ibuprofeno\", \"400mg\", \"3 días\", \"Cada 8 horas\", \"1\"]\n"
                + "28. REPORTES Y ESTADÍSTICAS (REP):\n"
                + "   - LISREP[\"*\" o \"citas\" o \"servicios\" o \"ingresos\"] -> Generar el reporte general o el reporte individual con su respectivo gráfico.\n\n"
                + "========================================\n"
                + "NOTA: Las fechas deben ir en formato AAAA-MM-DD (Ej: 1995-05-15).\n"
                + "(El porcentaje es un número decimal que representa la participación del propietario en la clínica, por ejemplo, 25 para un 25% de participación)"
                + "(El código de usuario es generado automáticamente por el sistema, no es necesario enviarlo, primera letra del apellido mayuscula + CI)"
                + "(La foto se carga mediante un archivo adjunto al correo)"
                + "========================================\n";

        try {
            smtpService.sendEmail(to, "Manual de Comandos - OdontoCool", message);
        } catch (IOException e) {
            System.err.println("Error al enviar ayuda: " + e.getMessage());
        }
    }
}
